name: Run Twitter Bot    
on:
  schedule:
    - cron: "0 7 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Setup Python 🔧
        uses: actions/setup-python@v2
        with:
           python-version: 3.8 #install the python needed
      - name: Execute twitter-bot 🚀
        working-directory: ./twitter-bot
        run: |
          pip3 install -r requirements.txt
          python bot.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
